//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH
    {
        public KH()
        {
            this.Phieux = new HashSet<Phieu>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
    
        public virtual ICollection<Phieu> Phieux { get; set; }
    }
}
