//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC
    {
        public NCC()
        {
            this.SPs = new HashSet<SP>();
        }
    
        public int MaNCC { get; set; }
        public string TenNCC { get; set; }
    
        public virtual ICollection<SP> SPs { get; set; }
    }
}
