//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        public NV()
        {
            this.Phieux = new HashSet<Phieu>();
            this.Phieux1 = new HashSet<Phieu>();
        }
    
        public int MaNV { get; set; }
        public string TenNV { get; set; }
    
        public virtual ICollection<Phieu> Phieux { get; set; }
        public virtual ICollection<Phieu> Phieux1 { get; set; }
    }
}
