//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu
    {
        public int MaPhieu { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual NV NV { get; set; }
        public virtual NV NV1 { get; set; }
        public virtual PhieuGiao PhieuGiao { get; set; }
        public virtual PhieuHD PhieuHD { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
