//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QLBH_WinDBContext : DbContext
    {
        public QLBH_WinDBContext()
            : base("name=QLBH_WinDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KH> KHs { get; set; }
        public DbSet<NCC> NCCs { get; set; }
        public DbSet<NV> NVs { get; set; }
        public DbSet<Phieu> Phieux { get; set; }
        public DbSet<PhieuGiao> PhieuGiaos { get; set; }
        public DbSet<PhieuHD> PhieuHDs { get; set; }
        public DbSet<PhieuHDChiTiet> PhieuHDChiTiets { get; set; }
        public DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public DbSet<PhieuNhapChiTiet> PhieuNhapChiTiets { get; set; }
        public DbSet<SP> SPs { get; set; }
        public DbSet<SPLoai> SPLoais { get; set; }
        public DbSet<SPNhom> SPNhoms { get; set; }
    
        public virtual int SPNhom_Sua(Nullable<int> maNhomSP, string tenNhomSP)
        {
            var maNhomSPParameter = maNhomSP.HasValue ?
                new ObjectParameter("MaNhomSP", maNhomSP) :
                new ObjectParameter("MaNhomSP", typeof(int));
    
            var tenNhomSPParameter = tenNhomSP != null ?
                new ObjectParameter("TenNhomSP", tenNhomSP) :
                new ObjectParameter("TenNhomSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPNhom_Sua", maNhomSPParameter, tenNhomSPParameter);
        }
    
        public virtual int SPNhom_Them(Nullable<int> maNhomSP, string tenNhomSP)
        {
            var maNhomSPParameter = maNhomSP.HasValue ?
                new ObjectParameter("MaNhomSP", maNhomSP) :
                new ObjectParameter("MaNhomSP", typeof(int));
    
            var tenNhomSPParameter = tenNhomSP != null ?
                new ObjectParameter("TenNhomSP", tenNhomSP) :
                new ObjectParameter("TenNhomSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPNhom_Them", maNhomSPParameter, tenNhomSPParameter);
        }
    
        public virtual int SPNhom_Xoa(Nullable<int> maNhomSP)
        {
            var maNhomSPParameter = maNhomSP.HasValue ?
                new ObjectParameter("MaNhomSP", maNhomSP) :
                new ObjectParameter("MaNhomSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPNhom_Xoa", maNhomSPParameter);
        }
    }
}
