//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SP()
        {
            this.PhieuHDChiTiets = new HashSet<PhieuHDChiTiet>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public string TenSP { get; set; }
        public string HinhSP { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual NCC NCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuHDChiTiet> PhieuHDChiTiets { get; set; }
        public virtual SPLoai SPLoai { get; set; }
    }
}
