//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPLoai
    {
        public SPLoai()
        {
            this.SPs = new HashSet<SP>();
        }
    
        public int MaLoaiSP { get; set; }
        public Nullable<int> MaNhomSP { get; set; }
        public string TenLoaiSP { get; set; }
    
        public virtual ICollection<SP> SPs { get; set; }
        public virtual SPNhom SPNhom { get; set; }
    }
}
